version: '3.7'

services:
  laravel-app:
    build:
      context: '.'
    container_name: [COMPLETE]-app
    volumes:
      - .:/var/www/html
    ports:
      - ${APP_PORT}:80
    networks:
      backend:
        aliases:
          - [COMPLETE]-app

  mysql-db:
    image: mysql:8.0
    container_name: [COMPLETE]-db
    volumes:
      - persistent:/var/lib/mysql
    ports: 
      - ${HOST_PORT}:${DB_PORT}
    command: --default-authentication-plugin=mysql_native_password  
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}    
    networks:
      backend:
        aliases:
          - [COMPLETE]-db

networks:
  backend:
    name: backend-network

volumes:
    persistent:
